### PR TITLE
Project: Authentication for an application

### PR DESCRIPTION
**Pull request by verissimohenry**
This assignment consists of using the Devise gem to have a first approach at authentication in rails. Building an application that allows users to create posts and the authors of the posts are displayed only if as a User you are logged in.

### CODE REVIEW

**Review by peterrobert — CHANGES_REQUESTED** [review]
### INVALID ♻️ 🛑 

Hello, @verissimohenry good effort submitting your project for a review. However, I could not review your project because of the following reasons ⬇️ 

- [ ] Kindly add a descriptive readme file. This will ensure that your project is professional. ⬇️ 
descriptive_readme

- [ ] Kindly add a descriptive pull request message. Remember a descriptive pull request message should have a title and some bullet points explaining what you have worked on in this project ⬇️ 
descriptive_prs


But no worries just update the two points above and submit your project for another review.

### HAPPY CODING 💻

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @verissimohenry :wave: 
### HIGHLIGHTS 💯 
- You have a well descriptive and professional README
- Your PR message is well detailed

## REQUIRED

* [ ] When I tried to create a post, I got the error below:
image
* [x] As a signed-in user you can create new post ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_post_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
* [x] As a signed-in user you can see post's author ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_see_author_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
* [x] As a guest you can see only post's text ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/guest_can_see_only_posts_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
* [x] The sign up and sign in form should be created by the devise gem([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_up_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49722686/))

#### Authentication and User setup

* [x] The application should have Sign in/Sign out links present in any view of the app ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_in_out_link_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49722686/))
* [x] You're to use application layout for sign-in and sign-out links.


## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- It creates the application routes using `resources :posts, only: [:new, :create, :index]` :+1: 
- Post `belongs_to` a `user` :100: 

To improve :factory_worker: [REQUIRED]:

- [ ] When I tried to create a post, I got the error below:

To fix it, I suggest that you add an `attribute` called '`user_id`' in Post table. It should be a `foreign key`.

- [ ]  **Please work on the previous TSE requirements.**

Nice to have :smiley: [OPTIONAL]

- [ ]  Files not related to the project should not be committed and added to `.gitignore` (e.g.
.vscode ) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Review by MkrtichSargsyan — CHANGES_REQUESTED** [review]
## _Status:_ Changes Requested :recycle:

## Hello Verissimo Verissimo

Good job on implementing the changes requested. However, there are some changes that you need to make in order to get your project approved

- [x] You still have this error.
I got this error when I try to create a new post
cacac


## OPTIONAL


Please, make the REQUIRED changes and submit your request again! :grinning:
Good luck. 

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Review by BrianSammit — APPROVED** [review]
STATUS: APPROVED :green_circle: :clap: 
-------------
Hello @verissimohenry you did a great job working on the required changes :muscle: :+1:
-------------
Now you can merge this branch :100: :smile: 
HAPPY CODING!! AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

tenor

**Pull request merged**
